site_name: Python Anglian Water
theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.progress
site_url: https://pyanglianwater.ha.system32.uk
plugins:
  - search
  - awesome-pages